# Generated by Django 3.0.5 on 2020-06-05 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(default='')),
                ('password', models.TextField(default='')),
                ('login', models.TextField(default='')),
                ('fullname', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(default='')),
                ('password', models.TextField(default='')),
                ('login', models.TextField(default='')),
                ('fullname', models.TextField(default='')),
                ('parent_number', models.TextField(default='')),
                ('parent_telegram', models.TextField(default='')),
                ('group', models.TextField(default='')),
                ('course', models.TextField(default='')),
                ('images_urls', models.ManyToManyField(blank=True, related_name='faces', to='main.Face')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
    ]
