# Generated by Django 3.0.5 on 2020-06-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='login',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
