# Generated by Django 3.0.5 on 2020-06-09 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200609_0939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Security',
        ),
    ]
