# Generated by Django 3.0.5 on 2020-06-10 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200609_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
    ]
