# Generated by Django 3.0.7 on 2020-08-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_botuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_telegram',
        ),
    ]
